<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>universal_controller</name>
  <version>0.0.1</version>
  <description>ROS2 Swerve Drive Controller for Infantry and sentry Robot</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO</license>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <depend>rclcpp</depend>
  <depend>custom_msgs</depend>

  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>rcl_interfaces</depend>
  <depend>sp_msgs</depend>
  <depend>dji_referee_protocol</depend>

  <test_depend>ament_copyright</test_depend>    <!-- 保留：检查版权声明（通用） -->
  <test_depend>ament_lint_auto</test_depend>    <!-- 核心：自动查找所有 lint 测试 -->
  <test_depend>ament_lint_common</test_depend>  <!-- 通用 lint 工具（C++/Python） -->
  <test_depend>ament_cmake_gtest</test_depend>  <!-- C++ 单元测试框架（GTest） -->
  <test_depend>ament_cmake_pytest</test_depend> <!-- 可选：如果混合 Python 测试 -->

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>